name: Pyblish Python Wheels

on:
  push:
    branches: ["dev"]

env:
  BUILD_TYPE: Release

jobs:

  build_x86:
    runs-on: ubuntu-22.10

    steps:
      - uses: actions/checkout@v3

      - uses: pypa/cibuildwheel@v2.11.3
        with:
          output-dir: dist

      - name: publish to test-pypi
        uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          user: __token__
          password: ${{ secrets.TWINE_API }}
          verbose: true
          print_hash: true
  
  build_aarch64:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
      - uses: pypa/cibuildwheel@v2.11.3
        with:
          arch: aarch64
          output-dir: dist

      - name: publish to test-pypi
        uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          user: __token__
          password: ${{ secrets.TWINE_API }}
          verbose: true
          print_hash: true  