name: Pyblish Python Wheels

on:
  push:
    branches: ["dev"]

env:
  BUILD_TYPE: Release

jobs:

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-11]

    steps:
      - uses: actions/checkout@v3

      - uses: pypa/cibuildwheel@v2.12.0
        with:
          output-dir: dist

      - name: publish to test-pypi
        uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          user: __token__
          password: ${{ secrets.TWINE_API }}
          verbose: true
          print_hash: true
