name: Pyblish Python Wheels

on:
  push:
    branches: ["dev"]

env:
  BUILD_TYPE: Release

jobs:

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-11]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: crazy-max/ghaction-setup-docker@v1.0.0
        with:
          version: 23.0.1
      - uses: docker/setup-qemu-action@v2.1.0

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --platform linux
        
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
  
  
  publish_wheels:
    name: Publish wheels to pypi
    runs-on: ubuntu-20.04
    needs: build_wheels
    
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          path: ./dist/

      - name: publish to test-pypi
        uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          user: __token__
          password: ${{ secrets.TWINE_API }}
          verbose: true
          print_hash: true
